#! /bin/bash
set -e

floyd init cifar10/jupyter

data_output_id=$(cat floyd/ids.yml | shyaml get-value data.output)
model_output_id=$(cat floyd/ids.yml | shyaml get-value train.output)

floyd run \
  --cpu \
  --env tensorflow:py2 \
  --data $data_output_id:data \
  --data $model_output_id:model \
  --mode jupyter
